import { MenuItem, ShopSetting } from './types';

export const initialShopSetting: ShopSetting = {
  id: 'default_setting',
  nameEn: 'Ameer Muaviya Burger Point',
  nameUr: 'امیر معاویہ برگر پوائنٹ',
  phone: '0300-9642811',
  locationEn: 'Main Bazaar, Near Al-Razi Hospital Road, Nokhar',
  locationUr: 'مین بازار، نزْد الرازی ہسپتال روڈ، نوکھر',
  openTime: '12:00 PM',
  closeTime: '12:00 AM',
  isOpen: true,
  announcement: 'خوش آمدید! گرما گرم اور خستہ انڈہ برگر، چکن برگر اور شاورما کے لیے ابھی آرڈر کریں - نوکھر میں ہوم ڈلیوری دستیاب ہے!',
};

export const initialMenuItems: MenuItem[] = [
  {
    id: 'item_single_egg',
    nameEn: 'Single Egg Burger',
    nameUr: 'سنگل انڈہ برگر (انڈہ شامی)',
    description: 'Crispy fried egg, spiced beef/chicken shami kabab, crunchy onion, coleslaw, mint raita & special tangy burger chutney on a toasted sesame bun.',
    price: 130,
    category: 'Burgers',
    image: '/images/single-egg-burger.jpg',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: 'item_double_egg',
    nameEn: 'Double Egg Burger',
    nameUr: 'ڈبل انڈہ برگر (اسپیشل)',
    description: 'Double golden fried eggs, double shami kabab, fresh crispy salad, secret burger spice blend, creamy mayo & zesty desi raita.',
    price: 180,
    category: 'Burgers',
    image: '/images/double-egg-burger.jpg',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: 'item_chicken_burger',
    nameEn: 'Crispy Chicken Zinger Burger',
    nameUr: 'چکن زنگر برگر',
    description: 'Golden crunchy chicken breast fillet, melted cheddar cheese, fresh iceberg lettuce, and signature spicy garlic mayo in a soft brioche bun.',
    price: 260,
    category: 'Burgers',
    image: '/images/crispy-chicken-burger.jpg',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    id: 'item_shawarma_special',
    nameEn: 'Special Chicken Shawarma',
    nameUr: 'اسپیشل چکن شاورما',
    description: 'Succulent marinated grilled chicken, pickled cucumber, crispy fries, special garlic sauce (Toum), wrapped in soft fresh pita bread.',
    price: 170,
    category: 'Shawarma',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 4,
  },
  {
    id: 'item_cheese_shawarma',
    nameEn: 'Chicken Cheese Shawarma',
    nameUr: 'چکن پنیر شاورما (چیزی)',
    description: 'Shredded roasted spiced chicken loaded with melted mozzarella & cheddar cheese, garlic mayo and hot chili sauce.',
    price: 220,
    category: 'Shawarma',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 5,
  },
  {
    id: 'item_masala_fries',
    nameEn: 'Crispy Masala Fries',
    nameUr: 'کرسپی مصالحہ فرائز',
    description: 'Golden crispy potato chips tossed in special Nokhar chaat masala and herbs, served with spicy garlic ketchup.',
    price: 120,
    category: 'Fries & Sides',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 6,
  },
  {
    id: 'item_chicken_roll',
    nameEn: 'Chicken Paratha Roll',
    nameUr: 'چکن پراٹھا رول',
    description: 'Crispy fried paratha stuffed with juicy chicken boti chunks, sliced red onions and thick mint chutney.',
    price: 210,
    category: 'Shawarma',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 7,
  },
  {
    id: 'item_cold_drinks',
    nameEn: 'Chilled Soft Drink (500ml)',
    nameUr: 'ٹھنڈی کولڈ ڈرنک (پیپسی / 7 اپ / میرنڈا)',
    description: 'Ice cold refreshing beverage bottle (Pepsi, 7Up, Mirinda, Mountain Dew, or Pakola).',
    price: 90,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 8,
  },
];
